import { Country } from './Country';
import { Region } from './Region';
import { Nullable } from './Nullable';

export type Address = {
    prefix?: Nullable<string>;
    firstName: string;
    middleName?: Nullable<string>;
    lastName: string;
    gender?: Nullable<string>;
    address1: string;
    address1Street: Nullable<string>;
    address1No: Nullable<string>;
    address2?: Nullable<string>;
    address2Comment: Nullable<string>;
    address2Comment2?: Nullable<string>;
    company?: Nullable<string>;
    city: string;
    postcode: string;
    phone: string;
    country: Country;
    region?: Region;
    isDefaultBilling: boolean;
    isDefaultShipping: boolean;
    isOffice: boolean;
    isUspAlternativeDeliveryPermission: Nullable<boolean>;
    uspAlternativeDeliveryComment: Nullable<string>;
    isBilling: boolean;
    pupLabelName?: Nullable<string>;
    pupConsigneeStreet1?: Nullable<string>;
    pupLabelStreet?: Nullable<string>;
    pupZip?: Nullable<string>;
    pupCity?: Nullable<string>;
    pupApid?: Nullable<string>;
    pupReference?: Nullable<string>;
    createdAt: string;
    updatedAt: string;
    link?: Nullable<string>;
    id: string;
    subscriptions?: $TSFixMe;
};